name: Halo3TickrateThingCPP CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up MSVC
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
    
    - name: Build project
      run: msbuild Halo3TickrateThingCPP.sln /p:Configuration=Release /p:Platform=x64
    
    - name: Upload release executable
      uses: actions/upload-release-asset@v1
      with:
        asset-path: Halo3TickrateThingCPP\bin\Release\Halo3TickrateThingCPP.exe  # Replace with the path to your release executable
        asset-name: YourExecutable.exe  # Replace with the desired name of the asset
        repo-token: ${{ secrets.GITHUB_TOKEN }}
