name: Halo3TickrateThingCPP CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'
    
    - name: Build project
      run: msbuild.exe Halo3TickrateThingCPP.sln /p:Configuration=Release /p:Platform=x64
    
    - name: Upload release executable
      uses: actions/upload-release-asset@v1
      with:
        asset-path: Halo3TickrateThingCPP\bin\Release\Halo3TickrateThingCPP.exe  # Replace with the path to your release executable
        asset-name: Halo3TickrateThingCPP.exe  # Replace with the desired name of the asset
        repo-token: ${{ secrets.GITHUB_TOKEN }}
