name: Halo3TickrateThingCPP CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build project
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace mcr.microsoft.com/windows/servercore:ltsc2019 powershell -Command "msbuild Halo3TickrateThingCPP.sln /p:Configuration=Release /p:Platform=x64"
    
    - name: Upload release executable
      uses: actions/upload-release-asset@v1
      with:
        asset-path: Halo3TickrateThingCPP\bin\Release\Halo3TickrateThingCPP.exe  # Replace with the path to your release executable
        asset-name: Halo3TickrateThingCPP.exe  # Replace with the desired name of the asset
        repo-token: ${{ secrets.GITHUB_TOKEN }}
