name: Halo3TickrateThingCPP CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up MSVC
      uses: microsoft/setup-msvc@v1
      with:
        msvc-version: '2019'  # Use '2019' for MSVC 2019
        
    - name: Build project
      run: |
        "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Halo3TickrateThingCPP.sln /p:Configuration=Release /p:Platform=x64
    
    - name: Upload release executable
      uses: actions/upload-release-asset@v1
      with:
        asset-path: Halo3TickrateThingCPP\bin\Release\YourExecutable.exe  # Replace with the path to your release executable
        asset-name: YourExecutable.exe  # Replace with the desired name of the asset
        repo-token: ${{ secrets.GITHUB_TOKEN }}
